REPLACE INTO role VALUES (1,'ADMIN');
REPLACE INTO role VALUES (2,'MECHANIC');

REPLACE INTO user_role VALUES (1,1);
REPLACE INTO user_role VALUES (2,2);
REPLACE INTO user_role VALUES (3,2);
REPLACE INTO user_role VALUES (4,2);
REPLACE INTO user_role VALUES (5,1);